Update pre-commit script & structure, added chakraUI

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -9,16 +9,16 @@ yarn pretty ||
     echo '❌ Unable to format your code!';
     false;
 )
-echo '✅Code is Pretty now.';
+echo '✅ Code is Pretty now.';
 
 # Check ESLint Standards
-yarn check-lint ||
+(yarn check-lint && yarn pre-commit-lint) ||
 (
         echo '😤👋😤 Follow lint standards 😤👋😤 
                 ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
         false; 
 )
-echo '✅No Linting issue found.';
+echo '✅ No Linting issue found.';
 
 # Check tsconfig standards
 yarn check-types ||
@@ -27,6 +27,14 @@ yarn check-types ||
             Types check failed! Make the changes required above.'
     false;
 )
-echo '✅No Typescript type issue found.';
-echo '✅✅✅ Success... Committing code. ✅✅✅'
+echo '✅ No Typescript types issue found.';
+
+yarn build ||
+(
+    echo '❌ Build failed ❌
+            Types check failed! Make the changes required above.'
+    false;
+)
+echo '✅ Build successfully.';
+echo '✅💯👍 Success... Committing code. 👍💯✅'
 
